# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deebd19a615034f166e746e89b174ab3542247755357136c60cad6728a81f8f95dadfde27c62db634ec16056b60ef103c2d417ac2354c818cae10847af000bec

test:
  secret_key_base: 07f3b64ea0cebee6b286e9cd005ff90ff89805d116427a3c8c7bfbe879e68a3d9a7989ece9b032bf5e86fcfe779bcff3de571af7c3cbbbc40ae0cd266e366be1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
